name: donate
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.3
  google_maps_flutter: ^2.2.8
  geolocator: ^10.1.0
  get_it: ^7.6.6
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.6
  flutter_native_splash: ^2.3.7
  firebase_core: ^2.24.2
  custom_info_window: ^1.0.1
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
